// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnA9PJ-GMlhvy2IPhwgOVhKr3T6Zk8w80',
    appId: '1:202516331845:web:a8aa96e75948bb62d5122c',
    messagingSenderId: '202516331845',
    projectId: 'thiya-fashion-stores',
    authDomain: 'thiya-fashion-stores.firebaseapp.com',
    storageBucket: 'thiya-fashion-stores.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeiLDCF9o5rD523B3il0nr67qIacrsSeI',
    appId: '1:202516331845:android:a21ec144cc0cdb9ed5122c',
    messagingSenderId: '202516331845',
    projectId: 'thiya-fashion-stores',
    storageBucket: 'thiya-fashion-stores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNDEcO3qhV7DnuRhCK2LPF215kR751rs4',
    appId: '1:202516331845:ios:303a4d284b05b389d5122c',
    messagingSenderId: '202516331845',
    projectId: 'thiya-fashion-stores',
    storageBucket: 'thiya-fashion-stores.firebasestorage.app',
    iosBundleId: 'com.example.thiyaFashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNDEcO3qhV7DnuRhCK2LPF215kR751rs4',
    appId: '1:202516331845:ios:303a4d284b05b389d5122c',
    messagingSenderId: '202516331845',
    projectId: 'thiya-fashion-stores',
    storageBucket: 'thiya-fashion-stores.firebasestorage.app',
    iosBundleId: 'com.example.thiyaFashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnA9PJ-GMlhvy2IPhwgOVhKr3T6Zk8w80',
    appId: '1:202516331845:web:4eddf5769af4ed0bd5122c',
    messagingSenderId: '202516331845',
    projectId: 'thiya-fashion-stores',
    authDomain: 'thiya-fashion-stores.firebaseapp.com',
    storageBucket: 'thiya-fashion-stores.firebasestorage.app',
  );
}
